Задание к уроку "Ассоциации моделей"
dionixs/test-guru pull request #4
Opened 2024-07-26 18:33 UTC by dionixs

2024-07-27 14:42 UTC, VidgarVii requested changes

2024-07-27 14:42 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
рекомендуется сначала писать все `belongs_to`, а уже после них все `has_many` ассоциации

2024-07-27 14:42 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :categories
Тест принадлежит категории

2024-07-27 14:42 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :questions
что произойдет с ответами, если вопрос удалили? - ответы ссылаются на вопрос
сейчас при попытке удаления `question` будет ошибка на уровне БД, благодаря тому что `question_id` указан, как внешний ключ в таблице `answers`

также рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций и выбрасывают ошибку, если объекта не существует
(в таблице `answers` останется в поле `question_id` со ссылкой на несуществующий объект класса `Question`, если к примеру поле не обозначено, как внешний ключ и база разрешит удалить объект)

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении
(опция `dependent: ...`)

2024-07-27 14:42 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2024-07-29 07:30 UTC, VidgarVii requested changes

2024-07-29 07:30 UTC, VidgarVii commented on db/migrate/20240716105702_create_questions.rb
> +      t.references :test, null: false, foreign_key: { on_delete: :cascade }
on_delete: :cascade можно обеспечипь средствами рельсы

2024-07-29 07:30 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :user_tests, dependent: :delete_all
при has_many through достаточно указать 1 раз dependent

2024-07-29 07:30 UTC, VidgarVii commented on app/models/test.rb
>    # названий всех Тестов у которых Категория называется определённым образом
с использованием ассоциации аргумент в методе `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

2024-07-29 07:30 UTC, VidgarVii commented on app/models/user.rb
>    # и возвращает список всех Тестов, которые проходит
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

2024-07-29 10:05 UTC, dionixs commented on db/migrate/20240716105702_create_questions.rb
> +      t.references :test, null: false, foreign_key: { on_delete: :cascade }
А при удалении теста тогда как лучше сделать? Пытаюсь удалить тест: `Test.first.destroy`
Получаю ошибку: 
```
PG::ForeignKeyViolation: ERROR:  update or delete on table "questions" violates foreign key constraint "fk_rails_3d5ed4418f" on table "answers" (ActiveRecord::InvalidForeignKey)
DETAIL:  Key (id)=(3) is still referenced from table "answers".
```

Для этого нужно использовать колбэк before_destroy? И удалять вопросы которые принадлежат конкретному тесту?

2024-07-29 14:25 UTC, VidgarVii requested changes

2024-07-29 14:25 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins(:user_tests)
И ещё раз. У тебя есть ассоциация, которая вернёт нужные тесты. Тут джойн не нужен.

2024-07-29 14:25 UTC, VidgarVii commented on app/models/test.rb
> +    joins(:category).where(categories: { title: })
Тут хорошо бы каждый вызов метода вынести на новую строчку, как было. Будет смотреться на много лучше.

2024-07-29 15:47 UTC, merged